/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppModerationRouteImport } from './routes/_app.moderation'
import { Route as AppAnimalsRouteImport } from './routes/_app.animals'
import { Route as AppAnimalsIdRouteImport } from './routes/_app.animals.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsRoute = AppAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalsIdRoute = AppAnimalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAnimalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/animals': typeof AppAnimalsRouteWithChildren
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/animals/$id': typeof AppAnimalsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/animals': typeof AppAnimalsRouteWithChildren
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/animals/$id': typeof AppAnimalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/animals': typeof AppAnimalsRouteWithChildren
  '/_app/moderation': typeof AppModerationRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/animals/$id': typeof AppAnimalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/animals'
    | '/moderation'
    | '/notifications'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/animals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/animals'
    | '/moderation'
    | '/notifications'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/'
    | '/animals/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/animals'
    | '/_app/moderation'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/'
    | '/_app/animals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals': {
      id: '/_app/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AppAnimalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animals/$id': {
      id: '/_app/animals/$id'
      path: '/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AppAnimalsIdRouteImport
      parentRoute: typeof AppAnimalsRoute
    }
  }
}

interface AppAnimalsRouteChildren {
  AppAnimalsIdRoute: typeof AppAnimalsIdRoute
}

const AppAnimalsRouteChildren: AppAnimalsRouteChildren = {
  AppAnimalsIdRoute: AppAnimalsIdRoute,
}

const AppAnimalsRouteWithChildren = AppAnimalsRoute._addFileChildren(
  AppAnimalsRouteChildren,
)

interface AppRouteChildren {
  AppAnimalsRoute: typeof AppAnimalsRouteWithChildren
  AppModerationRoute: typeof AppModerationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnimalsRoute: AppAnimalsRouteWithChildren,
  AppModerationRoute: AppModerationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
